# Lang
language: es

# Dark Mode
dark: false

# Header
menu:
  Infinito Parra: /

# Your Feed Location
#rss: /atom.xml

# Content
fancybox: true


# Miscellaneous
google_analytics:
favicon: /favicon.ico
twitter:
google_plus:
fb_admins:
fb_app_id:


# Profile
nickname: Infinito Parra
description: <h3>Poeta infinito en un mundo finito</h3><br /><p>Jose María Parra López es el autor de [Ciento once sonetos](111-sonetos/), [En la crisálida de luz y viento](En-la-crisalida-de-luz-y-viento) y la breve novela [Las alas del Universo](). En ambas, el autor intenta desarraigarse de los dogmas para liberar el alma a través de la eternidad y de lo infinito, considerándolos contenidos en el instante. En sus versos y en su prosa, el pensamiento se confunde con el alma, capaz de cargar la inmensidad del Cosmos a través de las propias ideas, con tal fuerza, que nos hace pensar en que el Universo es sin que necesariamente el tiempo transcurra, delimitado y definido así simplemente por su existencia. </p>

# Load fontawesome icons? Also see the links option
icons: false

# Footer area links
# NOTICE) If you set "icons: false" link names will be clear text
# If "icons: true" link names will interpreted as fontawesome icon names
# NOTICE) Use the fontawesome icon names without the fa- prefix (http://fontawesome.io/cheatsheet/)
links:
  En la crisálida de luz y viento: En-la-crisalida-de-luz-y-viento/
  Ciento once sonetos: 111-sonetos/


# nav position (top, left. top is default)
nav: left

# Info
archive_footer_content: José María Parra intenta responder a esta pregunta con versos que avanzan de lo material a lo inmaterial, de la realidad a los conceptos y alternan así entre lo corpóreo y lo espiritual conectando la materia con el inmenso y poderoso vacío del cielo, que deja ese hueco para permitir el suceder, la vida y la muerte.
post_footer_content: José María Parra intenta responder a esta pregunta con versos que avanzan de lo material a lo inmaterial, de la realidad a los conceptos y alternan así entre lo corpóreo y lo espiritual conectando la materia con el inmenso y poderoso vacío del cielo, que deja ese hueco para permitir el suceder, la vida y la muerte.

# Gitment
gitment:
  owner:
  repo:
  client:
    id:
    secret:

# If you want to use valine,you should get the appId and appKey form https://leancloud.cn ,more setting please see https://valine.js.org
valine:
  enable: false # !!if you want use valine comment system,please set enable: true
  appId:  #your leancloud appId
  appKey:  #your leancloud appKey
  guest_info: nick,mail,link #valine comment header info
  placeholder: Just go go # valine comment input placeholder(like: Please leave your footprints )
  avatar: mm # gravatar style https://valine.js.org/avatar
  pageSize: 10 # comment list page size
  verify: false # valine verify code (true/false)
  notify: false # valine mail notify (true/false)
  lang: zh-cn
